name: Deploy FlowFi Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create Service Account File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json

      - name: Deploy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json
        run: |
          firebase deploy --only hosting --project flowfi-1106
